import {StyleSheet} from 'react-native';

import {withOpacity} from '../../utils/colorUtils';

export const createStyles = (theme: any) =>
  StyleSheet.create({
    container: {flex: 1, backgroundColor: theme.colors.background},
    // D1：预览区顶着顶栏，去顶部 padding；左右/下保留
    content: {paddingHorizontal: 16, paddingBottom: 16, gap: 12},
    card: {
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius[theme.shapeRoles.card],
      padding: 12,
      gap: 10,
    },
    cardTitle: {...theme.typography.titleS, fontWeight: '600', color: theme.colors.onSurface},
    hint: {...theme.typography.captionM, color: theme.colors.onSurfaceVariant},
    modelChip: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius[theme.shapeRoles.pill],
      paddingHorizontal: 14,
      paddingVertical: 10,
      gap: 8,
    },
    modelChipText: {
      flex: 1,
      ...theme.typography.uiM,
      fontWeight: '600',
      color: theme.colors.onSurface,
    },
    // 胶囊内文本区（点击展开下拉）
    modelChipMain: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    modelChipStatus: {...theme.typography.uiS, color: theme.colors.primary},
    // 模型胶囊内快速加载按钮（未加载时显示，不展开下拉）
    chipLoadBtn: {
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: theme.radius[theme.shapeRoles.pill],
      backgroundColor: theme.colors.primary,
    },
    chipLoadText: {
      ...theme.typography.uiS,
      color: theme.colors.onPrimary,
      fontWeight: '600',
    },
    dropPanel: {
      marginTop: 6,
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius[theme.shapeRoles.surface],
      padding: 12,
      gap: 8,
      // 锚定下拉：盖在后续内容之上
      elevation: 8,
      shadowColor: '#000',
      shadowOpacity: 0.2,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 4},
    },
    modelRow: {
      paddingVertical: 10,
      paddingHorizontal: 10,
      borderRadius: theme.radius[theme.shapeRoles.inputSmall],
      backgroundColor: theme.colors.surface,
      flexDirection: 'row',
      alignItems: 'center',
    },
    modelRowMain: {flex: 1, paddingRight: 8},
    modelRowSelected: {borderWidth: 1, borderColor: theme.colors.primary},
    modelName: {...theme.typography.uiM, color: theme.colors.onSurface},
    modelNote: {
      ...theme.typography.captionS,
      color: theme.colors.onSurfaceVariant,
      marginTop: 2,
    },
    // 行内加载/卸载按钮（操作就近，状态可见；卸载需二次确认）
    rowActionBtn: {
      minWidth: 56,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: theme.radius[theme.shapeRoles.inputSmall],
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
    },
    rowActionBtnUnload: {
      backgroundColor: 'transparent',
      borderWidth: 1,
      borderColor: theme.colors.danger,
    },
    rowActionText: {
      ...theme.typography.uiS,
      color: theme.colors.onPrimary,
      fontWeight: '600',
    },
    rowActionTextUnload: {color: theme.colors.danger},
    resultWrap: {position: 'relative'},
    preview: {width: '100%', aspectRatio: 1, borderRadius: theme.radius.s},
    // 0 页编辑槽：上传大按钮 / 待编辑图预览 + 重新上传
    editSlot: {
      aspectRatio: 1,
      borderRadius: theme.radius.s,
      backgroundColor: theme.colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
    },
    editSlotImg: {width: '100%', height: '100%', borderRadius: theme.radius.s},
    uploadBig: {
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: theme.colors.outline,
      borderRadius: theme.radius.m,
      paddingHorizontal: 32,
      paddingVertical: 28,
    },
    uploadBigIcon: {
      fontSize: 40,
      color: theme.colors.primary,
      fontWeight: '300',
    },
    uploadBigText: {
      ...theme.typography.bodyM,
      color: theme.colors.onSurface,
      fontWeight: '600',
    },
    uploadBigHint: {...theme.typography.captionS, color: theme.colors.onSurfaceVariant},
    uploadFab: {
      position: 'absolute',
      bottom: 10,
      backgroundColor: withOpacity(theme.colors.info, 0.9),
      borderRadius: theme.radius.s,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    uploadFabText: {
      ...theme.typography.uiS,
      color: theme.colors.onInfo,
      fontWeight: '600',
    },
    genOverlay: {
      ...StyleSheet.absoluteFillObject,
      // 浅色圆角（与卡片设计语言统一；助手气泡点缀色 + 95% 不透明）：出图盖住预览区
      backgroundColor: theme.colors.assistantBubbleBackground + 'F2',
      borderRadius: theme.radius.s,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 16,
      gap: 8,
    },
    genOverlayEdit: {
      // 编辑态：更低不透明度，底图可见
      backgroundColor: theme.colors.assistantBubbleBackground + 'A6',
    },
    // 三点波浪动效容器/圆点
    genDotsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      height: 32,
    },
    genDot: {
      width: 10,
      height: 10,
      borderRadius: theme.radius[theme.shapeRoles.circle],
      backgroundColor: theme.colors.primary,
    },
    genOverlayTitle: {
      ...theme.typography.uiM,
      color: theme.colors.onSurface,
      fontWeight: '600',
      marginTop: 4,
    },
    overlayText: {...theme.typography.captionS, color: theme.colors.onSurfaceVariant},
    overlayStage: {...theme.typography.captionS, color: theme.colors.onSurfaceVariant},
    actionRow: {flexDirection: 'row', gap: 8},
    actionBtn: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 8,
      borderRadius: theme.radius.s,
      backgroundColor: theme.colors.surface,
    },
    actionText: {...theme.typography.uiS, color: theme.colors.onSurface},
    // 语义彩色点缀（DESIGN_SPEC §1.3：bg/onX 成对使用）
    actionSave: {backgroundColor: theme.colors.success},
    actionTextOnSuccess: {
      ...theme.typography.uiS,
      color: theme.colors.onSuccess,
      fontWeight: '600',
    },
    actionEdit: {backgroundColor: theme.colors.info},
    actionTextOnInfo: {
      ...theme.typography.uiS,
      color: theme.colors.onInfo,
      fontWeight: '600',
    },
    actionReuse: {backgroundColor: theme.colors.warning},
    actionTextOnWarning: {
      ...theme.typography.uiS,
      color: theme.colors.onWarning,
      fontWeight: '600',
    },
    actionDelete: {backgroundColor: theme.colors.danger},
    actionTextOnDanger: {
      ...theme.typography.uiS,
      color: theme.colors.onDanger,
      fontWeight: '600',
    },
    badgeSd3: {color: theme.colors.badgeSd35, fontWeight: '700'},
    badgeZ: {color: theme.colors.badgeZImage, fontWeight: '700'},
    badgeDream: {color: theme.colors.badgeDreamlite, fontWeight: '700'},
    // 实验性徽章：警示色（模型可能不可用，与操作按钮橙区分）
    badgeExp: {color: theme.colors.warning, fontWeight: '700', ...theme.typography.captionS},
    // D1 顶栏触发胶囊（挂在 IMAGE_GEN headerRight；生图域色 12% 透明底）
    // B5（DESIGN_SPEC §8 Gap Ledger）：headerRight 右缘对齐内容区右边距（16dp）
    triggerWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginRight: 16,
    },
    triggerPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: withOpacity(theme.colors.domain.imageGen, 0.12),
      borderRadius: theme.radius.full,
      paddingVertical: 4,
      paddingHorizontal: 10,
      maxWidth: 180,
    },
    triggerText: {
      ...theme.typography.uiS,
      fontWeight: '600',
      color: theme.colors.onSurface,
      flexShrink: 1,
    },
    triggerArrow: {...theme.typography.captionS, color: theme.colors.domain.imageGen},
    triggerLoadBtn: {
      paddingHorizontal: 10,
      paddingVertical: 3,
      borderRadius: theme.radius.full,
      backgroundColor: theme.colors.primary,
    },
    triggerLoadText: {
      ...theme.typography.captionS,
      color: theme.colors.onPrimary,
      fontWeight: '600',
    },
    dropOverlay: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 50,
      elevation: 50,
    },
    dropBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0,0,0,0.25)',
    },
    dropPanelAbs: {
      position: 'absolute',
      // D1：overlay 起于 AppBar 下沿（overlayTop），面板紧随共后
      top: 6,
      left: 16,
      right: 16,
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius[theme.shapeRoles.surface],
      padding: 12,
      gap: 8,
      elevation: 12,
      shadowColor: '#000',
      shadowOpacity: 0.25,
      shadowRadius: 10,
      shadowOffset: {width: 0, height: 6},
    },
    // 信息条：压在预览图顶部（半透明黑底白字，模型 · 耗时 · 分辨率）
    infoOverlay: {
      position: 'absolute',
      top: 8,
      left: 8,
      right: 8,
      backgroundColor: 'rgba(0, 0, 0, 0.55)',
      borderRadius: theme.radius.s,
      paddingHorizontal: 10,
      paddingVertical: 4,
      alignItems: 'center',
    },
    infoOverlayText: {
      color: '#fff',
      ...theme.typography.captionS,
    },
    toastBar: {
      position: 'absolute',
      top: 8,
      left: 8,
      right: 8,
      backgroundColor: 'rgba(0,0,0,0.75)',
      borderRadius: theme.radius.s,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    toastText: {...theme.typography.uiS, color: '#fff'},
    historyHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    historyHeaderActions: {flexDirection: 'row', alignItems: 'center', gap: 14},
    uploadText: {
      ...theme.typography.uiS,
      color: theme.colors.info,
      fontWeight: '600',
    },
    manageText: {...theme.typography.uiS, color: theme.colors.primary},
    historyItem: {marginRight: 8, position: 'relative'},
    historyThumb: {width: 72, height: 72, borderRadius: theme.radius.s},
    historyKindBadge: {
      position: 'absolute',
      bottom: 2,
      right: 2,
      backgroundColor: withOpacity(theme.colors.info, 0.9),
      borderRadius: theme.radius.xs,
      paddingHorizontal: 4,
      paddingVertical: 1,
    },
    historyKindText: {
      ...theme.typography.captionS,
      color: theme.colors.onInfo,
      fontWeight: '600',
    },
    historySel: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      borderRadius: theme.radius.s,
      backgroundColor: 'rgba(0,0,0,0.5)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    historySelText: {color: '#fff', ...theme.typography.titleM, fontWeight: '700'},
    button: {
      backgroundColor: theme.colors.primary,
      borderRadius: theme.radius.s,
      paddingVertical: 12,
      alignItems: 'center',
    },
    buttonRow: {flexDirection: 'row', gap: 10},
    buttonEdit: {flex: 1, backgroundColor: theme.colors.info},
    buttonGen: {flex: 1},
    buttonSecondary: {backgroundColor: theme.colors.surface,},
    buttonDanger: {backgroundColor: theme.colors.error},
    buttonDisabled: {backgroundColor: theme.colors.surface,},
    buttonText: {
      color: theme.colors.onPrimary,
      ...theme.typography.uiM,
      fontWeight: '600',
    },
    buttonTextOnInfo: {color: theme.colors.onInfo},
    buttonTextOnDanger: {color: theme.colors.onError},
    error: {...theme.typography.uiS, color: theme.colors.error},
    input: {
      borderWidth: 1,
      borderColor: theme.colors.outline,
      borderRadius: theme.radius[theme.shapeRoles.inputSmall],
      padding: 12,
      minHeight: 72,
      color: theme.colors.onSurface,
      textAlignVertical: 'top',
    },
    inputSmall: {minHeight: 44, padding: 8},
    advToggle: {...theme.typography.uiS, color: theme.colors.primary},
    promptHint: {...theme.typography.captionS, color: theme.colors.onSurfaceVariant},
    promptHintWarn: {...theme.typography.captionS, color: theme.colors.error},
    paramRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 10,
    },
    paramLabel: {...theme.typography.captionM, color: theme.colors.onSurfaceVariant},
    paramInput: {
      borderWidth: 1,
      borderColor: theme.colors.outline,
      borderRadius: theme.radius[theme.shapeRoles.inputSmall],
      paddingHorizontal: 10,
      paddingVertical: 6,
      width: 60,
      color: theme.colors.onSurface,
    },
    sizeBtn: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: theme.radius.s,
      backgroundColor: theme.colors.surface,
      alignItems: 'center',
    },
    sizeBtnSelected: {borderWidth: 1, borderColor: theme.colors.primary},
    sizeBtnText: {...theme.typography.uiS, color: theme.colors.onSurface},
    sizeBtnSub: {
      ...theme.typography.captionS,
      color: theme.colors.onSurfaceVariant,
      marginTop: 2,
    },
    statusPanel: {marginTop: 6, gap: 3},
    progressTrack: {
      height: 8,
      borderRadius: theme.radius.xs,
      backgroundColor: withOpacity(theme.colors.shadow, 0.08),
      overflow: 'hidden',
    },
    progressTrackW70: {width: '70%'},
    progressBarFill: {
      height: 8,
      backgroundColor: theme.colors.primary,
      borderRadius: theme.radius.xs,
    },
    progressText: {
      ...theme.typography.captionS,
      color: theme.colors.onSurfaceVariant,
      marginTop: 2,
    },
    stageText: {...theme.typography.captionS, color: theme.colors.primary},
    readyText: {...theme.typography.uiS, color: theme.colors.primary, marginTop: 4},
    fullscreenBackdrop: {flex: 1, backgroundColor: '#000'},
    fullscreenTouch: {flex: 1, alignItems: 'center', justifyContent: 'center'},
    fullscreenImage: {width: '100%', height: '100%'},
    fullscreenHint: {
      position: 'absolute',
      bottom: 24,
      alignSelf: 'center',
      color: '#fff',
      ...theme.typography.uiS,
    },
  });
