import {StyleSheet} from 'react-native';

export const createStyles = (theme: any) =>
  StyleSheet.create({
    container: {flex: 1, backgroundColor: theme.colors.background},
    content: {padding: 16, gap: 12},
    card: {
      backgroundColor: theme.colors.surface,
      borderRadius: 12,
      padding: 12,
      gap: 10,
    },
    cardTitle: {fontSize: 15, fontWeight: '600', color: theme.colors.onSurface},
    hint: {fontSize: 12, color: theme.colors.onSurfaceVariant},
    modelChip: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.colors.surface,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 10,
      gap: 8,
    },
    modelChipText: {
      flex: 1,
      fontSize: 13,
      fontWeight: '600',
      color: theme.colors.onSurface,
    },
    // 胶囊内文本区（点击展开下拉）
    modelChipMain: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    modelChipStatus: {fontSize: 12, color: theme.colors.primary},
    // 模型胶囊内快速加载按钮（未加载时显示，不展开下拉）
    chipLoadBtn: {
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 999,
      backgroundColor: theme.colors.primary,
    },
    chipLoadText: {
      fontSize: 12,
      color: theme.colors.onPrimary,
      fontWeight: '600',
    },
    dropPanel: {
      marginTop: 6,
      backgroundColor: theme.colors.surface,
      borderRadius: 12,
      padding: 12,
      gap: 8,
      // 锚定下拉：盖在后续内容之上
      elevation: 8,
      shadowColor: '#000',
      shadowOpacity: 0.2,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 4},
    },
    modelRow: {
      paddingVertical: 10,
      paddingHorizontal: 10,
      borderRadius: 8,
      backgroundColor: theme.colors.surfaceVariant,
      flexDirection: 'row',
      alignItems: 'center',
    },
    modelRowMain: {flex: 1, paddingRight: 8},
    modelRowSelected: {borderWidth: 1, borderColor: theme.colors.primary},
    modelName: {fontSize: 13, color: theme.colors.onSurface},
    modelNote: {
      fontSize: 11,
      color: theme.colors.onSurfaceVariant,
      marginTop: 2,
    },
    // 行内加载/卸载按钮（操作就近，状态可见；卸载需二次确认）
    rowActionBtn: {
      minWidth: 56,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: 6,
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
    },
    rowActionBtnUnload: {
      backgroundColor: 'transparent',
      borderWidth: 1,
      borderColor: '#c62828',
    },
    rowActionText: {fontSize: 12, color: '#fff', fontWeight: '600'},
    rowActionTextUnload: {color: '#c62828'},
    resultWrap: {position: 'relative'},
    preview: {width: '100%', aspectRatio: 1, borderRadius: 8},
    // 0 页编辑槽：上传大按钮 / 待编辑图预览 + 重新上传
    editSlot: {
      aspectRatio: 1,
      borderRadius: 8,
      backgroundColor: theme.colors.surfaceVariant,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
    },
    editSlotImg: {width: '100%', height: '100%', borderRadius: 8},
    uploadBig: {
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: theme.colors.outline,
      borderRadius: 12,
      paddingHorizontal: 32,
      paddingVertical: 28,
    },
    uploadBigIcon: {
      fontSize: 40,
      color: theme.colors.primary,
      fontWeight: '300',
    },
    uploadBigText: {
      fontSize: 15,
      color: theme.colors.onSurface,
      fontWeight: '600',
    },
    uploadBigHint: {fontSize: 11, color: theme.colors.onSurfaceVariant},
    uploadFab: {
      position: 'absolute',
      bottom: 10,
      backgroundColor: 'rgba(21,101,192,0.9)',
      borderRadius: 6,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    uploadFabText: {fontSize: 12, color: '#fff', fontWeight: '600'},
    genOverlay: {
      ...StyleSheet.absoluteFillObject,
      // 浅色圆角（与卡片设计语言统一；助手气泡点缀色 + 95% 不透明）：出图盖住预览区
      backgroundColor: theme.colors.assistantBubbleBackground + 'F2',
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 16,
      gap: 8,
    },
    genOverlayEdit: {
      // 编辑态：更低不透明度，底图可见
      backgroundColor: theme.colors.assistantBubbleBackground + 'A6',
    },
    // 三点波浪动效容器/圆点
    genDotsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      height: 32,
    },
    genDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: theme.colors.primary,
    },
    genOverlayTitle: {
      fontSize: 14,
      color: theme.colors.onSurface,
      fontWeight: '600',
      marginTop: 4,
    },
    overlayText: {fontSize: 11, color: theme.colors.onSurfaceVariant},
    overlayStage: {fontSize: 10, color: theme.colors.onSurfaceVariant},
    actionRow: {flexDirection: 'row', gap: 8},
    actionBtn: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 8,
      borderRadius: 8,
      backgroundColor: theme.colors.surfaceVariant,
    },
    actionText: {fontSize: 12, color: theme.colors.onSurface},
    actionTextLight: {fontSize: 12, color: '#fff', fontWeight: '600'},
    actionDanger: {color: theme.colors.error},
    // 语义彩色点缀
    actionSave: {backgroundColor: '#2e7d32'},
    actionEdit: {backgroundColor: '#1565c0'},
    actionReuse: {backgroundColor: '#ef6c00'},
    actionDelete: {backgroundColor: '#c62828'},
    badgeSd3: {color: '#8e24aa', fontWeight: '700'},
    badgeZ: {color: '#00838f', fontWeight: '700'},
    badgeDream: {color: '#d81b60', fontWeight: '700'},
    // 实验性徽章：琥珀警示色（模型可能不可用，与操作按钮橙区分）
    badgeExp: {color: '#f57c00', fontWeight: '700', fontSize: 11},
    dropOverlay: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 50,
      elevation: 50,
    },
    dropBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0,0,0,0.25)',
    },
    dropPanelAbs: {
      position: 'absolute',
      top: 64,
      left: 16,
      right: 16,
      backgroundColor: theme.colors.surface,
      borderRadius: 12,
      padding: 12,
      gap: 8,
      elevation: 12,
      shadowColor: '#000',
      shadowOpacity: 0.25,
      shadowRadius: 10,
      shadowOffset: {width: 0, height: 6},
    },
    watermark: {fontSize: 10, color: theme.colors.onSurfaceVariant},
    toastBar: {
      position: 'absolute',
      top: 8,
      left: 8,
      right: 8,
      backgroundColor: 'rgba(0,0,0,0.75)',
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    toastText: {fontSize: 12, color: '#fff'},
    historyHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    historyHeaderActions: {flexDirection: 'row', alignItems: 'center', gap: 14},
    uploadText: {fontSize: 12, color: '#1565c0', fontWeight: '600'},
    manageText: {fontSize: 12, color: theme.colors.primary},
    historyItem: {marginRight: 8, position: 'relative'},
    historyThumb: {width: 72, height: 72, borderRadius: 8},
    historyKindBadge: {
      position: 'absolute',
      bottom: 2,
      right: 2,
      backgroundColor: 'rgba(21,101,192,0.9)',
      borderRadius: 4,
      paddingHorizontal: 4,
      paddingVertical: 1,
    },
    historyKindText: {fontSize: 9, color: '#fff', fontWeight: '600'},
    historySel: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      borderRadius: 8,
      backgroundColor: 'rgba(0,0,0,0.5)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    historySelText: {color: '#fff', fontSize: 20, fontWeight: '700'},
    button: {
      backgroundColor: theme.colors.primary,
      borderRadius: 8,
      paddingVertical: 12,
      alignItems: 'center',
    },
    buttonRow: {flexDirection: 'row', gap: 10},
    buttonEdit: {flex: 1, backgroundColor: '#1565c0'},
    buttonGen: {flex: 1},
    buttonSecondary: {backgroundColor: theme.colors.surfaceVariant},
    buttonDanger: {backgroundColor: theme.colors.error},
    buttonDisabled: {backgroundColor: theme.colors.surfaceVariant},
    buttonText: {color: '#fff', fontSize: 14, fontWeight: '600'},
    error: {fontSize: 12, color: theme.colors.error},
    input: {
      borderWidth: 1,
      borderColor: theme.colors.outline,
      borderRadius: 8,
      padding: 12,
      minHeight: 72,
      color: theme.colors.onSurface,
      textAlignVertical: 'top',
    },
    inputSmall: {minHeight: 44, padding: 8},
    advToggle: {fontSize: 12, color: theme.colors.primary},
    promptHint: {fontSize: 10, color: theme.colors.onSurfaceVariant},
    promptHintWarn: {fontSize: 10, color: theme.colors.error},
    paramRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 10,
    },
    paramLabel: {fontSize: 13, color: theme.colors.onSurfaceVariant},
    paramInput: {
      borderWidth: 1,
      borderColor: theme.colors.outline,
      borderRadius: 8,
      paddingHorizontal: 10,
      paddingVertical: 6,
      width: 60,
      color: theme.colors.onSurface,
    },
    sizeBtn: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 8,
      backgroundColor: theme.colors.surfaceVariant,
      alignItems: 'center',
    },
    sizeBtnSelected: {borderWidth: 1, borderColor: theme.colors.primary},
    sizeBtnText: {fontSize: 12, color: theme.colors.onSurface},
    sizeBtnSub: {
      fontSize: 10,
      color: theme.colors.onSurfaceVariant,
      marginTop: 2,
    },
    statusPanel: {marginTop: 6, gap: 3},
    progressTrack: {
      height: 8,
      borderRadius: 4,
      backgroundColor: 'rgba(0,0,0,0.08)',
      overflow: 'hidden',
    },
    progressTrackW70: {width: '70%'},
    progressBarFill: {
      height: 8,
      backgroundColor: theme.colors.primary,
      borderRadius: 4,
    },
    progressText: {
      fontSize: 11,
      color: theme.colors.onSurfaceVariant,
      marginTop: 2,
    },
    stageText: {fontSize: 10, color: theme.colors.primary},
    readyText: {fontSize: 12, color: theme.colors.primary, marginTop: 4},
    fullscreenBackdrop: {flex: 1, backgroundColor: '#000'},
    fullscreenTouch: {flex: 1, alignItems: 'center', justifyContent: 'center'},
    fullscreenImage: {width: '100%', height: '100%'},
    fullscreenHint: {
      position: 'absolute',
      bottom: 24,
      alignSelf: 'center',
      color: '#fff',
      fontSize: 12,
    },
  });
